### ISSUE TITLE
Always loads in the on state and then transitions to the off state

### ISSUE THREAD

**Issue by mlenser** [ziscloud/angular-bootstrap-toggle#2]
You can see this behavior on the issue I created for translations: http://embed.plnkr.co/KoxNXyUnN4te54yjnwrH/

**Comment by ziscloud** [comment]
Thank you very much, and I have fixed this issued, please check following plnkr (forked from yours):
http://run.plnkr.co/djaKS3R3MV5fbh1l/
I will update github ASAP to release this fix.

**Comment by mlenser** [comment]
Plunk doesn't work, but I trust that it'll work.
Thanks!

I'll try to create a reproducible plunker or github project or something for the translation issue when I get some time. Otherwise this is a great little module.

**Comment by ziscloud** [comment]
Sorry for the broken link, please visit http://embed.plnkr.co/0ksOglQa7vYXnZZcLf5p/.

**Comment by mlenser** [comment]
Hmm I still see it load on the green state and then animate to the red state in that plunk.

**Comment by ziscloud** [comment]
Yes, it is because the state is determinate in the link phase of the directive, I have tried to solve it, but... if you have any solution, please share.

**Comment by thrinay** [comment]
Is this problem fixed yet? Because, whenever I am trying to switch states with toggle staying on the parent state it always switches from off to on but when it is switched back to off toggle, then it stays the same

**Comment by rousspb** [comment]
The library is amazing but this double switch looks like a bug. Any update on this? Would it be fixed?

**Comment by bertysentry** [comment]
This has been fixed in the 0.4.0 version, thanks!

**Comment by bertysentry** [comment]
This has been fixed in version 0.4.0 (0.4.1 available now), thanks!
